version: '3.8'

services:
  server:
    # restart: always
    build:
      context: ./server
    ports:
      - '8080:3000'
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=library
      - DATABASE_PORT=5432
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=library
    ports:
      - '5432:5432'
    volumes:
      - ./database:/docker-entrypoint-initdb.d
